plugins
{
    id 'fabric-loom' version "${loom_version}"
}

base
{
    archivesBaseName("${mod_id}-fabric-${mod_version}+${minecraft_version}")
}

repositories
{
    mavenCentral()
    mavenLocal()
    
    maven
    {
        url = 'https://maven.minecraftforge.net/'
    }
}

dependencies
{
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    
    modImplementation 'com.github.glitchfiend:TerraBlender-fabric:1.21.5-5.0.0.1'
    
    compileOnly(project(":common"))
}

loom
{
    
    accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    
    mixin
    {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    
    runs
    {
        
        named("client")
        {
            client()
            ideConfigGenerated(true)
            configName("Fabric Minecraft Client")
            runDir("run")
        }
        
        named("server")
        {
            server()
            ideConfigGenerated(true)
            configName("Fabric Minecraft Server")
            runDir("run")
        }
    }
}

processResources
{
    filesMatching("fabric.mod.json")
    {
        expand project.properties
    }
    
    from project(":common").sourceSets.main.resources
}

java
{
    withSourcesJar()
    //withJavadocJar()
    
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar
{
    inputs.property "archivesName", project.base.archivesName
    
    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

tasks.withType(JavaCompile).configureEach
{
    options.encoding = "UTF-8"
    
    source(project(":common").sourceSets.main.allSource)
}